language: scala

sudo: false

scala:
   - 2.10.6
   - 2.11.8
   - 2.12.1

jdk:
  - oraclejdk8

script:
  - sbt ++${TRAVIS_SCALA_VERSION} "project $TEST_PROJECT" compile test:compile test

env:
  matrix:
  - TEST_PROJECT="rootJVM"
  - TEST_PROJECT="rootJS"

cache:
  directories:
    - $HOME/.ivy2/cache
